; Since Generation IV, the move priority ranges from -7 to 5.
; To avoid working with negative numbers, we shift the priority 
; range to be from 0 to 12.
PriorityMovesList:
	db POUND,        7
	db KARATE_CHOP,  7
	db DOUBLESLAP,   7
	db COMET_PUNCH,  7
	db MEGA_PUNCH,   7
	db PAY_DAY,      7
	db FIRE_PUNCH,   7
	db ICE_PUNCH,    7
	db THUNDERPUNCH, 7
	db SCRATCH,      7
	db VICEGRIP,     7
	db GUILLOTINE,   7
	db RAZOR_WIND,   7
	db SWORDS_DANCE, 7
	db CUT,          7
	db GUST,         7
	db WING_ATTACK,  7
	db WHIRLWIND,    1
	db FLY,          7
	db BIND,         7
	db SLAM,         7
	db VINE_WHIP,    7
	db STOMP,        7
	db DOUBLE_KICK,  7
	db MEGA_KICK,    7
	db JUMP_KICK,    7
	db ROLLING_KICK, 7
	db SAND_ATTACK,  7
	db HEADBUTT,     7
	db HORN_ATTACK,  7
	db FURY_ATTACK,  7
	db HORN_DRILL,   7
	db TACKLE,       7
	db BODY_SLAM,    7
	db WRAP,         7
	db TAKE_DOWN,    7
	db THRASH,       7
	db DOUBLE_EDGE,  7
	db TAIL_WHIP,    7
	db POISON_STING, 7
	db TWINEEDLE,    7
	db PIN_MISSILE,  7
	db LEER,         7
	db BITE,         7
	db GROWL,        7
	db ROAR,         1
	db SING,         7
	db SUPERSONIC,   7
	db SONICBOOM,    7
	db DISABLE,      7
	db ACID,         7
	db EMBER,        7
	db FLAMETHROWER, 7
	db MIST,         7
	db WATER_GUN,    7
	db HYDRO_PUMP,   7
	db SURF,         7
	db ICE_BEAM,     7
	db BLIZZARD,     7
	db PSYBEAM,      7
	db BUBBLEBEAM,   7
	db AURORA_BEAM,  7
	db HYPER_BEAM,   7
	db PECK,         7
	db DRILL_PECK,   7
	db SUBMISSION,   7
	db LOW_KICK,     7
	db COUNTER,      2
	db SEISMIC_TOSS, 7
	db STRENGTH,     7
	db ABSORB,       7
	db MEGA_DRAIN,   7
	db LEECH_SEED,   7
	db GROWTH,       7
	db RAZOR_LEAF,   7
	db SOLARBEAM,    7
	db POISONPOWDER, 7
	db STUN_SPORE,   7
	db SLEEP_POWDER, 7
	db PETAL_DANCE,  7
	db STRING_SHOT,  7
	db DRAGON_RAGE,  7
	db FIRE_SPIN,    7
	db THUNDERSHOCK, 7
	db THUNDERBOLT,  7
	db THUNDER_WAVE, 7
	db THUNDER,      7
	db ROCK_THROW,   7
	db EARTHQUAKE,   7
	db FISSURE,      7
	db DIG,          7
	db TOXIC,        7
	db CONFUSION,    7
	db PSYCHIC_M,    7
	db HYPNOSIS,     7
	db MEDITATE,     7
	db AGILITY,      7
	db QUICK_ATTACK, 8
	db RAGE,         7
	db TELEPORT,     1
	db NIGHT_SHADE,  7
	db MIMIC,        7
	db SCREECH,      7
	db DOUBLE_TEAM,  7
	db RECOVER,      7
	db HARDEN,       7
	db MINIMIZE,     7
	db SMOKESCREEN,  7
	db CONFUSE_RAY,  7
	db WITHDRAW,     7
	db DEFENSE_CURL, 7
	db BARRIER,      7
	db LIGHT_SCREEN, 7
	db HAZE,         7
	db REFLECT,      7
	db FOCUS_ENERGY, 7
	db BIDE,         8
	db METRONOME,    7
	db MIRROR_MOVE,  7
	db SELFDESTRUCT, 7
	db EGG_BOMB,     7
	db LICK,         7
	db SMOG,         7
	db SLUDGE,       7
	db BONE_CLUB,    7
	db FIRE_BLAST,   7
	db WATERFALL,    7
	db CLAMP,        7
	db SWIFT,        7
	db SKULL_BASH,   7
	db SPIKE_CANNON, 7
	db CONSTRICT,    7
	db AMNESIA,      7
	db KINESIS,      7
	db SOFTBOILED,   7
	db HI_JUMP_KICK, 7
	db GLARE,        7
	db DREAM_EATER,  7
	db POISON_GAS,   7
	db BARRAGE,      7
	db LEECH_LIFE,   7
	db LOVELY_KISS,  7
	db SKY_ATTACK,   7
	db TRANSFORM,    7
	db BUBBLE,       7
	db DIZZY_PUNCH,  7
	db SPORE,        7
	db FLASH,        7
	db PSYWAVE,      7
	db SPLASH,       7
	db ACID_ARMOR,   7
	db CRABHAMMER,   7
	db EXPLOSION,    7
	db FURY_SWIPES,  7
	db BONEMERANG,   7
	db REST,         7
	db ROCK_SLIDE,   7
	db HYPER_FANG,   7
	db SHARPEN,      7
	db CONVERSION,   7
	db TRI_ATTACK,   7
	db SUPER_FANG,   7
	db SLASH,        7
	db SUBSTITUTE,   7
	db STRUGGLE,     7
	db -1 ; end